name: Client Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  NODE_VERSION: 16.17.0
  TEST_RESULTS_DIRECTORY: .
  # Force a path with spaces and unicode chars to test extension works in these scenarios
  special-working-directory: './ğŸ ğŸ›'
  special-working-directory-relative: 'ğŸ ğŸ›'

jobs:
  build:
    name: TypeScript Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ env.special-working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.special-working-directory-relative }}

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.special-working-directory-relative }}/package-lock.json

      - name: Install Node dependencies
        run: npm ci
        shell: bash

      - name: Compile TS tests
        run: npm run pretest
        shell: bash

      - name: Run TS tests
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: npm run tests
          working-directory: ${{ env.special-working-directory }}
